"""initial_schema

Revision ID: 5edc5fb50c10
Revises: 
Create Date: 2026-07-09 02:48:34.852338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5edc5fb50c10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience_segments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('estimated_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bidding_strategies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('traffic_allocation', sa.Integer(), nullable=False),
    sa.Column('min_sample_size', sa.Integer(), nullable=True),
    sa.Column('max_duration_days', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('winner_variant_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_variant_id'], ['variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_campaign_id'), 'experiments', ['campaign_id'], unique=False)
    op.create_index('ix_experiments_campaign_status', 'experiments', ['campaign_id', 'status'], unique=False)
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_index('ix_experiments_status_dates', 'experiments', ['status', 'start_date', 'end_date'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_table('variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('traffic_pct', sa.Float(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'name', name='uq_variant_experiment_name')
    )
    op.create_index(op.f('ix_variants_experiment_id'), 'variants', ['experiment_id'], unique=False)
    op.create_table('advertisers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertisers_owner_id'), 'advertisers', ['owner_id'], unique=False)
    op.create_table('agent_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('tools_enabled', sa.JSON(), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_configs_user_id'), 'agent_configs', ['user_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('rate_limit_rps', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index('ix_api_keys_prefix_active', 'api_keys', ['key_prefix', 'is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('bucket', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'user_id', name='uq_assignment_experiment_user')
    )
    op.create_index(op.f('ix_assignments_experiment_id'), 'assignments', ['experiment_id'], unique=False)
    op.create_index('ix_assignments_user_experiment', 'assignments', ['user_id', 'experiment_id'], unique=False)
    op.create_index(op.f('ix_assignments_user_id'), 'assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_assignments_variant_id'), 'assignments', ['variant_id'], unique=False)
    op.create_table('experiment_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experiment_metrics_event_time', 'experiment_metrics', ['event_time'], unique=False)
    op.create_index(op.f('ix_experiment_metrics_experiment_id'), 'experiment_metrics', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_experiment_metrics_user_id'), 'experiment_metrics', ['user_id'], unique=False)
    op.create_index(op.f('ix_experiment_metrics_variant_id'), 'experiment_metrics', ['variant_id'], unique=False)
    op.create_index('ix_experiment_metrics_variant_metric', 'experiment_metrics', ['variant_id', 'metric_name'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_refresh_tokens_user_created', 'refresh_tokens', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_id', name='uq_user_permission')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('config_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('final_output', sa.Text(), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['agent_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_config_id'), 'agent_runs', ['config_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('advertiser_id', sa.Uuid(), nullable=True),
    sa.Column('bidding_strategy_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('daily_budget', sa.Float(), nullable=True),
    sa.Column('spent', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('target_cpa', sa.Float(), nullable=True),
    sa.Column('target_roas', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('frequency_cap', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bidding_strategy_id'], ['bidding_strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_advertiser_id'), 'campaigns', ['advertiser_id'], unique=False)
    op.create_index('ix_campaigns_advertiser_status', 'campaigns', ['advertiser_id', 'status'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_index('ix_campaigns_status_dates', 'campaigns', ['status', 'start_date', 'end_date'], unique=False)
    op.create_table('ab_tests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('traffic_split', sa.Float(), nullable=False),
    sa.Column('metric_target', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('winner', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ab_test_campaign_id', 'ab_tests', ['campaign_id'], unique=False)
    op.create_index('ix_ab_test_status', 'ab_tests', ['status'], unique=False)
    op.create_table('agent_memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_memories_created_at', 'agent_memories', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_memories_run_id'), 'agent_memories', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_memories_user_id'), 'agent_memories', ['user_id'], unique=False)
    op.create_index('ix_agent_memories_user_type', 'agent_memories', ['user_id', 'memory_type'], unique=False)
    op.create_table('agent_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('thought', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('tool_input', sa.JSON(), nullable=False),
    sa.Column('tool_output', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'step_number', name='uq_agent_step_run_number')
    )
    op.create_index(op.f('ix_agent_steps_run_id'), 'agent_steps', ['run_id'], unique=False)
    op.create_table('auction_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('impression_id', sa.String(length=255), nullable=False),
    sa.Column('ssp', sa.String(length=100), nullable=True),
    sa.Column('floor_price', sa.Float(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('geo', sa.String(length=50), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auction_requests_campaign_created', 'auction_requests', ['campaign_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_auction_requests_campaign_id'), 'auction_requests', ['campaign_id'], unique=False)
    op.create_index('ix_auction_requests_created_at', 'auction_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_auction_requests_impression_id'), 'auction_requests', ['impression_id'], unique=False)
    op.create_index(op.f('ix_auction_requests_request_id'), 'auction_requests', ['request_id'], unique=True)
    op.create_index(op.f('ix_auction_requests_user_id'), 'auction_requests', ['user_id'], unique=False)
    op.create_table('auctions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('impression_id', sa.String(length=255), nullable=False),
    sa.Column('floor_price', sa.Float(), nullable=False),
    sa.Column('winning_bid', sa.Float(), nullable=True),
    sa.Column('winning_dsp', sa.String(length=100), nullable=True),
    sa.Column('auction_type', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auction_campaign_id', 'auctions', ['campaign_id'], unique=False)
    op.create_index('ix_auction_created_at', 'auctions', ['created_at'], unique=False)
    op.create_table('campaign_audience_segments',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('audience_segment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['audience_segment_id'], ['audience_segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'audience_segment_id')
    )
    op.create_table('creatives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('asset_url', sa.String(length=512), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('call_to_action', sa.String(length=100), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('predicted_ctr', sa.Float(), nullable=True),
    sa.Column('fatigue_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_creatives_campaign_active', 'creatives', ['campaign_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_creatives_campaign_id'), 'creatives', ['campaign_id'], unique=False)
    op.create_index('ix_creatives_upload_time', 'creatives', ['created_at'], unique=False)
    op.create_table('daily_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('cpm', sa.Float(), nullable=False),
    sa.Column('cpc', sa.Float(), nullable=False),
    sa.Column('roi', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'campaign_id', name='uq_daily_metric_date_campaign')
    )
    op.create_index(op.f('ix_daily_metrics_campaign_id'), 'daily_metrics', ['campaign_id'], unique=False)
    op.create_index('ix_daily_metrics_date_campaign', 'daily_metrics', ['date', 'campaign_id'], unique=False)
    op.create_table('fraud_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_alerts_campaign_id'), 'fraud_alerts', ['campaign_id'], unique=False)
    op.create_index('ix_fraud_alerts_campaign_status', 'fraud_alerts', ['campaign_id', 'status'], unique=False)
    op.create_index('ix_fraud_alerts_detected_at', 'fraud_alerts', ['detected_at'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_status'), 'fraud_alerts', ['status'], unique=False)
    op.create_table('traffic_quality_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('geo', sa.String(length=50), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('ctr_score', sa.Float(), nullable=False),
    sa.Column('cvr_score', sa.Float(), nullable=False),
    sa.Column('bounce_score', sa.Float(), nullable=False),
    sa.Column('dwell_score', sa.Float(), nullable=False),
    sa.Column('interaction_score', sa.Float(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('anomaly_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_traffic_quality_scores_campaign_date', 'traffic_quality_scores', ['campaign_id', 'date'], unique=False)
    op.create_index(op.f('ix_traffic_quality_scores_campaign_id'), 'traffic_quality_scores', ['campaign_id'], unique=False)
    op.create_index('ix_traffic_quality_scores_date', 'traffic_quality_scores', ['date'], unique=False)
    op.create_table('ab_test_variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ab_test_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('traffic_pct', sa.Float(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ab_test_id'], ['ab_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ab_test_variant_ab_test_id', 'ab_test_variants', ['ab_test_id'], unique=False)
    op.create_index('ix_ab_test_variant_name', 'ab_test_variants', ['name'], unique=False)
    op.create_table('auction_bids',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('auction_request_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('creative_id', sa.Uuid(), nullable=True),
    sa.Column('dsp_name', sa.String(length=100), nullable=False),
    sa.Column('bid_amount', sa.Float(), nullable=False),
    sa.Column('ctr_estimate', sa.Float(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auction_request_id'], ['auction_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_bids_auction_request_id'), 'auction_bids', ['auction_request_id'], unique=False)
    op.create_index(op.f('ix_auction_bids_campaign_id'), 'auction_bids', ['campaign_id'], unique=False)
    op.create_index('ix_auction_bids_created_at', 'auction_bids', ['created_at'], unique=False)
    op.create_index(op.f('ix_auction_bids_creative_id'), 'auction_bids', ['creative_id'], unique=False)
    op.create_index(op.f('ix_auction_bids_dsp_name'), 'auction_bids', ['dsp_name'], unique=False)
    op.create_table('auction_wins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('auction_request_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('creative_id', sa.Uuid(), nullable=True),
    sa.Column('winning_bid', sa.Float(), nullable=False),
    sa.Column('second_price', sa.Float(), nullable=False),
    sa.Column('auction_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auction_request_id'], ['auction_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auction_request_id', name='uq_auction_wins_request')
    )
    op.create_index(op.f('ix_auction_wins_auction_request_id'), 'auction_wins', ['auction_request_id'], unique=False)
    op.create_index('ix_auction_wins_campaign_created', 'auction_wins', ['campaign_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_auction_wins_campaign_id'), 'auction_wins', ['campaign_id'], unique=False)
    op.create_table('bid_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('auction_id', sa.Uuid(), nullable=False),
    sa.Column('dsp_name', sa.String(length=100), nullable=False),
    sa.Column('bid_amount', sa.Float(), nullable=False),
    sa.Column('ctr_estimate', sa.Float(), nullable=False),
    sa.Column('was_winner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bid_record_auction_id', 'bid_records', ['auction_id'], unique=False)
    op.create_index('ix_bid_record_dsp_name', 'bid_records', ['dsp_name'], unique=False)
    op.create_table('conversion_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('conversion_value', sa.Float(), nullable=False),
    sa.Column('conversion_time', sa.DateTime(), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('geo', sa.String(length=50), nullable=True),
    sa.Column('creative_id', sa.Uuid(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversion_events_campaign_id'), 'conversion_events', ['campaign_id'], unique=False)
    op.create_index('ix_conversion_events_campaign_time', 'conversion_events', ['campaign_id', 'conversion_time'], unique=False)
    op.create_index(op.f('ix_conversion_events_user_id'), 'conversion_events', ['user_id'], unique=False)
    op.create_index('ix_conversion_events_user_time', 'conversion_events', ['user_id', 'conversion_time'], unique=False)
    op.create_table('attribution_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversion_event_id', sa.Uuid(), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('click_window_days', sa.Integer(), nullable=False),
    sa.Column('view_window_days', sa.Integer(), nullable=False),
    sa.Column('channel_credits', sa.JSON(), nullable=False),
    sa.Column('campaign_credits', sa.JSON(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversion_event_id'], ['conversion_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attribution_results_calculated_at', 'attribution_results', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_attribution_results_conversion_event_id'), 'attribution_results', ['conversion_event_id'], unique=False)
    op.create_index('ix_attribution_results_conversion_model', 'attribution_results', ['conversion_event_id', 'model_type'], unique=False)
    op.create_table('touchpoints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('creative_id', sa.Uuid(), nullable=True),
    sa.Column('touchpoint_seq', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('conversion_event_id', sa.Uuid(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversion_event_id'], ['conversion_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_touchpoints_campaign_id'), 'touchpoints', ['campaign_id'], unique=False)
    op.create_index('ix_touchpoints_conversion', 'touchpoints', ['conversion_event_id'], unique=False)
    op.create_index(op.f('ix_touchpoints_conversion_event_id'), 'touchpoints', ['conversion_event_id'], unique=False)
    op.create_index('ix_touchpoints_event_time', 'touchpoints', ['event_time'], unique=False)
    op.create_index('ix_touchpoints_user_campaign_seq', 'touchpoints', ['user_id', 'campaign_id', 'touchpoint_seq'], unique=False)
    op.create_index(op.f('ix_touchpoints_user_id'), 'touchpoints', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_touchpoints_user_id'), table_name='touchpoints')
    op.drop_index('ix_touchpoints_user_campaign_seq', table_name='touchpoints')
    op.drop_index('ix_touchpoints_event_time', table_name='touchpoints')
    op.drop_index(op.f('ix_touchpoints_conversion_event_id'), table_name='touchpoints')
    op.drop_index('ix_touchpoints_conversion', table_name='touchpoints')
    op.drop_index(op.f('ix_touchpoints_campaign_id'), table_name='touchpoints')
    op.drop_table('touchpoints')
    op.drop_index('ix_attribution_results_conversion_model', table_name='attribution_results')
    op.drop_index(op.f('ix_attribution_results_conversion_event_id'), table_name='attribution_results')
    op.drop_index('ix_attribution_results_calculated_at', table_name='attribution_results')
    op.drop_table('attribution_results')
    op.drop_index('ix_conversion_events_user_time', table_name='conversion_events')
    op.drop_index(op.f('ix_conversion_events_user_id'), table_name='conversion_events')
    op.drop_index('ix_conversion_events_campaign_time', table_name='conversion_events')
    op.drop_index(op.f('ix_conversion_events_campaign_id'), table_name='conversion_events')
    op.drop_table('conversion_events')
    op.drop_index('ix_bid_record_dsp_name', table_name='bid_records')
    op.drop_index('ix_bid_record_auction_id', table_name='bid_records')
    op.drop_table('bid_records')
    op.drop_index(op.f('ix_auction_wins_campaign_id'), table_name='auction_wins')
    op.drop_index('ix_auction_wins_campaign_created', table_name='auction_wins')
    op.drop_index(op.f('ix_auction_wins_auction_request_id'), table_name='auction_wins')
    op.drop_table('auction_wins')
    op.drop_index(op.f('ix_auction_bids_dsp_name'), table_name='auction_bids')
    op.drop_index(op.f('ix_auction_bids_creative_id'), table_name='auction_bids')
    op.drop_index('ix_auction_bids_created_at', table_name='auction_bids')
    op.drop_index(op.f('ix_auction_bids_campaign_id'), table_name='auction_bids')
    op.drop_index(op.f('ix_auction_bids_auction_request_id'), table_name='auction_bids')
    op.drop_table('auction_bids')
    op.drop_index('ix_ab_test_variant_name', table_name='ab_test_variants')
    op.drop_index('ix_ab_test_variant_ab_test_id', table_name='ab_test_variants')
    op.drop_table('ab_test_variants')
    op.drop_index('ix_traffic_quality_scores_date', table_name='traffic_quality_scores')
    op.drop_index(op.f('ix_traffic_quality_scores_campaign_id'), table_name='traffic_quality_scores')
    op.drop_index('ix_traffic_quality_scores_campaign_date', table_name='traffic_quality_scores')
    op.drop_table('traffic_quality_scores')
    op.drop_index(op.f('ix_fraud_alerts_status'), table_name='fraud_alerts')
    op.drop_index('ix_fraud_alerts_detected_at', table_name='fraud_alerts')
    op.drop_index('ix_fraud_alerts_campaign_status', table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_campaign_id'), table_name='fraud_alerts')
    op.drop_table('fraud_alerts')
    op.drop_index('ix_daily_metrics_date_campaign', table_name='daily_metrics')
    op.drop_index(op.f('ix_daily_metrics_campaign_id'), table_name='daily_metrics')
    op.drop_table('daily_metrics')
    op.drop_index('ix_creatives_upload_time', table_name='creatives')
    op.drop_index(op.f('ix_creatives_campaign_id'), table_name='creatives')
    op.drop_index('ix_creatives_campaign_active', table_name='creatives')
    op.drop_table('creatives')
    op.drop_table('campaign_audience_segments')
    op.drop_index('ix_auction_created_at', table_name='auctions')
    op.drop_index('ix_auction_campaign_id', table_name='auctions')
    op.drop_table('auctions')
    op.drop_index(op.f('ix_auction_requests_user_id'), table_name='auction_requests')
    op.drop_index(op.f('ix_auction_requests_request_id'), table_name='auction_requests')
    op.drop_index(op.f('ix_auction_requests_impression_id'), table_name='auction_requests')
    op.drop_index('ix_auction_requests_created_at', table_name='auction_requests')
    op.drop_index(op.f('ix_auction_requests_campaign_id'), table_name='auction_requests')
    op.drop_index('ix_auction_requests_campaign_created', table_name='auction_requests')
    op.drop_table('auction_requests')
    op.drop_index(op.f('ix_agent_steps_run_id'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index('ix_agent_memories_user_type', table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_user_id'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_run_id'), table_name='agent_memories')
    op.drop_index('ix_agent_memories_created_at', table_name='agent_memories')
    op.drop_table('agent_memories')
    op.drop_index('ix_ab_test_status', table_name='ab_tests')
    op.drop_index('ix_ab_test_campaign_id', table_name='ab_tests')
    op.drop_table('ab_tests')
    op.drop_index('ix_campaigns_status_dates', table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index('ix_campaigns_advertiser_status', table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_advertiser_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_agent_runs_user_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_config_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('user_roles')
    op.drop_table('user_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_user_created', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_experiment_metrics_variant_metric', table_name='experiment_metrics')
    op.drop_index(op.f('ix_experiment_metrics_variant_id'), table_name='experiment_metrics')
    op.drop_index(op.f('ix_experiment_metrics_user_id'), table_name='experiment_metrics')
    op.drop_index(op.f('ix_experiment_metrics_experiment_id'), table_name='experiment_metrics')
    op.drop_index('ix_experiment_metrics_event_time', table_name='experiment_metrics')
    op.drop_table('experiment_metrics')
    op.drop_index(op.f('ix_assignments_variant_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_user_id'), table_name='assignments')
    op.drop_index('ix_assignments_user_experiment', table_name='assignments')
    op.drop_index(op.f('ix_assignments_experiment_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index('ix_api_keys_prefix_active', table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_agent_configs_user_id'), table_name='agent_configs')
    op.drop_table('agent_configs')
    op.drop_index(op.f('ix_advertisers_owner_id'), table_name='advertisers')
    op.drop_table('advertisers')
    op.drop_index(op.f('ix_variants_experiment_id'), table_name='variants')
    op.drop_table('variants')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('ix_experiments_status_dates', table_name='experiments')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_index('ix_experiments_campaign_status', table_name='experiments')
    op.drop_index(op.f('ix_experiments_campaign_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_table('bidding_strategies')
    op.drop_table('audience_segments')
    # ### end Alembic commands ###
